-- =============================================
-- COURSES 테이블 시드 데이터 (5개 코스)
-- =============================================

INSERT INTO courses (id, region, title, subtitle, description, legend_summary, difficulty, mission_count, duration, price_1p, price_2p, thumbnail_url, video_url, status, created_at)
VALUES

-- 코스 1: 전주 도깨비
('course-jeonju-dokkaebi',
 'jeonju',
 '{"ko": "도깨비의 선물", "ja": "トッケビの贈り物", "en": "Gift of the Dokkaebi"}',
 '{"ko": "전주 한옥마을에서 도깨비를 만나다", "ja": "全州韓屋村でトッケビに出会う", "en": "Meet the Dokkaebi in Jeonju Hanok Village"}',
 '{"ko": "착한 나무꾼이 도깨비에게 노래를 불러주자 금은보화가 나오는 방망이를 선물 받는 이야기를 따라, 전주 한옥마을과 도깨비숲을 탐험합니다.", "ja": "優しい木こりがトッケビに歌を歌い、金銀財宝が出る棒をもらった物語に沿って、全州韓屋村とトッケビの森を探検します。", "en": "Follow the tale of a kind woodcutter who sang for the Dokkaebi and received a magical club, exploring Jeonju Hanok Village and Dokkaebi Forest."}',
 '{"ko": "착한 나무꾼이 산에서 도깨비를 만나 노래를 불러주자, 도깨비들이 기뻐하며 금은보화가 나오는 방망이를 선물했습니다. 이를 본 욕심쟁이 이웃이 따라했다가 오히려 벌을 받았습니다.", "ja": "心優しい木こりが山でトッケビに出会い歌を歌うと、トッケビたちは喜んで金銀財宝が出る魔法の棒を贈りました。これを見た欲張りな隣人が真似をしましたが、逆に罰を受けました。", "en": "A kind woodcutter met Dokkaebi in the mountains and sang for them. Delighted, the Dokkaebi gifted him a magical club that produced gold and silver. A greedy neighbor tried to copy him but was punished instead."}',
 'easy',
 8,
 '{"ko": "1일", "ja": "1日", "en": "1 day"}',
 29000,
 39000,
 '/images/courses/jeonju-dokkaebi-thumb.jpg',
 NULL,
 'active',
 NOW()
),

-- 코스 2: 통영 별주부전
('course-tongyeong-byeoljubu',
 'tongyeong',
 '{"ko": "별주부의 모험", "ja": "ピョルジュブの冒険", "en": "Adventure of Byeoljubu"}',
 '{"ko": "토끼와 자라의 바다 용궁 이야기", "ja": "ウサギとスッポンの海の龍宮物語", "en": "The Sea Palace Tale of Rabbit and Turtle"}',
 '{"ko": "바다 용왕의 병을 고치기 위해 토끼의 간을 구하러 육지로 올라온 자라(별주부)와, 꾀로 탈출하는 영리한 토끼의 이야기를 따라 통영과 비토섬을 탐험합니다.", "ja": "海の龍王の病を治すためにウサギの肝を求めて陸に上がったスッポン（ピョルジュブ）と、知恵で脱出する賢いウサギの物語に沿って、統営とビト島を探検します。", "en": "Follow the tale of the turtle Byeoljubu who came ashore to find a rabbit liver to cure the Sea King, and the clever rabbit who escaped by wit, exploring Tongyeong and Bito Island."}',
 '{"ko": "바다 용왕이 병에 걸려 토끼의 간이 필요하다는 처방을 받았습니다. 충신 자라(별주부)가 육지로 올라가 토끼를 속여 바다로 데려갔지만, 영리한 토끼는 간을 꺼내 육지에 두고 왔다는 꾀로 탈출했습니다.", "ja": "海の龍王が病にかかり、ウサギの肝が必要だという処方を受けました。忠臣のスッポン（ピョルジュブ）が陸に上がりウサギを騙して海に連れて行きましたが、賢いウサギは「肝を取り出して陸に置いてきた」という知恵で脱出しました。", "en": "The Sea King fell ill and was prescribed rabbit liver. The loyal turtle Byeoljubu tricked a rabbit into coming to the sea palace, but the clever rabbit escaped by claiming he had left his liver on land."}',
 'medium',
 8,
 '{"ko": "1박 2일", "ja": "1泊2日", "en": "2 days"}',
 29000,
 39000,
 '/images/courses/tongyeong-byeoljubu-thumb.jpg',
 NULL,
 'active',
 NOW()
),

-- 코스 3: 천안 능소전
('course-cheonan-nungso',
 'cheonan',
 '{"ko": "능소의 기다림", "ja": "ヌンソの待ち人", "en": "Nungso''s Waiting"}',
 '{"ko": "천안삼거리 능수버들 아래 사랑 이야기", "ja": "天安三叉路のしだれ柳の下の愛の物語", "en": "A Love Story Beneath the Willows of Cheonan"}',
 '{"ko": "아버지를 기다리며 버드나무를 심던 소녀 능소와, 과거 보러 가던 선비 박현수의 사랑 이야기를 따라 천안삼거리공원과 중앙시장을 탐험합니다.", "ja": "父を待ちながら柳を植えた少女ヌンソと、科挙試験に向かう書生パク・ヒョンスの愛の物語に沿って、天安三叉路公園と中央市場を探検します。", "en": "Follow the love story of Nungso, a girl who planted willows waiting for her father, and scholar Park Hyun-su, exploring Cheonan Samgeori Park and the central market."}',
 '{"ko": "아버지 유봉서가 전쟁터로 떠나며 어린 딸 능소를 천안삼거리 주막에 맡겼습니다. 능소는 아버지를 기다리며 매일 버드나무를 심었고, 훗날 과거 보러 가던 선비 박현수를 간병하며 사랑에 빠져 백년가약을 맺었습니다. 장원급제한 박현수가 돌아오자 능소가 가야금을 타며 천안 흥타령을 불렀습니다.", "ja": "父ユ・ボンソが戦場に向かう際、幼い娘ヌンソを天安三叉路の宿屋に預けました。ヌンソは父を待ちながら毎日柳を植え、やがて科挙に向かう途中で倒れた書生パク・ヒョンスを看病し、恋に落ちて結婚しました。首席合格したパク・ヒョンスが戻ると、ヌンソはカヤグムを弾きながら天安フンタリョンを歌いました。", "en": "Father Yu Bong-seo left his young daughter Nungso at a Cheonan Samgeori inn before heading to war. Nungso planted willows daily waiting for him. Years later, she nursed the ailing scholar Park Hyun-su, fell in love, and they married. When Park returned as the top exam graduate, Nungso played the gayageum and sang the Cheonan Heungtaryeong."}',
 'easy',
 7,
 '{"ko": "반나절~1일", "ja": "半日〜1日", "en": "Half day to 1 day"}',
 29000,
 39000,
 '/images/courses/cheonan-nungso-thumb.jpg',
 NULL,
 'coming_soon',
 NOW()
),

-- 코스 4: 용인 동화
('course-yongin-fairytale',
 'yongin',
 '{"ko": "동화 속으로", "ja": "童話の中へ", "en": "Into the Fairy Tales"}',
 '{"ko": "한국민속촌에서 전래동화 올스타를 만나다", "ja": "韓国民俗村で昔話オールスターに出会う", "en": "Meet All-Star Korean Fairy Tales at Folk Village"}',
 '{"ko": "콩쥐팥쥐, 흥부놀부, 혹부리영감, 선녀와 나무꾼, 금도끼 은도끼 — 한국 전래동화 다섯 편의 주인공들을 한국민속촌 안에서 한 번에 만나는 종합 모험 코스입니다.", "ja": "コンジュパッジュ、フンブノルブ、コブトリじいさん、仙女と木こり、金の斧銀の斧 — 韓国昔話5作品の主人公たちを韓国民俗村で一度に出会う総合冒険コースです。", "en": "Kongjwi & Patjwi, Heungbu & Nolbu, Old Man Wart, Fairy & Woodcutter, Gold Axe & Silver Axe — an all-in-one adventure meeting heroes of five Korean fairy tales at Korean Folk Village."}',
 '{"ko": "한국의 대표 전래동화 다섯 편을 한 곳에서 체험합니다. 착한 콩쥐가 새엄마의 구박을 이기고 행복을 찾는 이야기, 착한 흥부가 제비의 보은으로 부자가 되는 이야기, 혹부리영감이 도깨비에게 노래를 불러 혹을 떼는 이야기, 나무꾼이 사슴의 보은으로 선녀를 만나는 이야기, 정직한 나무꾼이 산신령에게 금도끼를 받는 이야기입니다.", "ja": "韓国を代表する昔話5編を一か所で体験します。善良なコンジュが継母のいじめに打ち勝つ話、善良なフンブがツバメの恩返しで富を得る話、コブトリじいさんがトッケビに歌を歌ってコブを取る話、木こりが鹿の恩返しで仙女に出会う話、正直な木こりが山の神から金の斧をもらう話です。", "en": "Experience five iconic Korean fairy tales in one place: Kongjwi overcoming her stepmother, Heungbu rewarded by a swallow, Old Man Wart singing for the Dokkaebi, a woodcutter meeting a fairy through a deer''s gratitude, and an honest woodcutter receiving a gold axe from the mountain spirit."}',
 'easy',
 8,
 '{"ko": "반나절", "ja": "半日", "en": "Half day"}',
 29000,
 39000,
 '/images/courses/yongin-fairytale-thumb.jpg',
 NULL,
 'coming_soon',
 NOW()
),

-- 코스 5: 이천 선녀와 나무꾼
('course-icheon-fairy',
 'icheon',
 '{"ko": "선녀의 날개옷", "ja": "仙女の羽衣", "en": "The Fairy''s Feathered Robe"}',
 '{"ko": "이천 효양산에서 하고로모 전설을 만나다", "ja": "利川ヒョヤン山で羽衣伝説に出会う", "en": "Discover the Hagoromo Legend at Icheon Hyoyangsan"}',
 '{"ko": "사슴을 구해준 나무꾼이 보은으로 선녀의 목욕 장소를 알게 되고, 날개옷을 숨겨 결혼하지만 결국 선녀가 하늘로 돌아가는 이야기를 따라 이천 효양산과 도예마을을 탐험합니다.", "ja": "鹿を助けた木こりが恩返しで仙女の沐浴場を知り、羽衣を隠して結婚しますが、やがて仙女が天に帰る物語に沿って、利川ヒョヤン山と陶芸村を探検します。", "en": "Follow the tale of a woodcutter who saved a deer and learned where fairies bathed, hid a feathered robe to marry a fairy, but ultimately lost her to the heavens, exploring Icheon Hyoyangsan and the pottery village."}',
 '{"ko": "가난한 나무꾼이 사냥꾼에게 쫓기는 사슴을 숨겨줬습니다. 사슴이 보은으로 선녀가 목욕하는 연못을 알려주며, 아이 셋을 낳기 전에는 날개옷을 돌려주지 말라고 충고했습니다. 나무꾼은 날개옷을 숨겨 선녀와 결혼하고 아이 둘을 낳았지만, 약속을 잊고 날개옷을 돌려주자 선녀는 아이들과 함께 하늘로 올라갔습니다.", "ja": "貧しい木こりが猟師に追われる鹿を匿いました。鹿は恩返しで仙女が沐浴する池の場所を教え、「子供が3人生まれる前に羽衣を返してはいけない」と忠告しました。木こりは羽衣を隠して仙女と結婚し子供を2人もうけましたが、約束を忘れて羽衣を返すと、仙女は子供たちを連れて天に昇りました。", "en": "A poor woodcutter hid a deer from hunters. In gratitude, the deer revealed where fairies bathed and warned him not to return the feathered robe until they had three children. The woodcutter hid the robe, married a fairy, and had two children, but forgot the warning and returned the robe. The fairy took the children and flew back to heaven."}',
 'easy',
 7,
 '{"ko": "반나절~1일", "ja": "半日〜1日", "en": "Half day to 1 day"}',
 29000,
 39000,
 '/images/courses/icheon-fairy-thumb.jpg',
 NULL,
 'coming_soon',
 NOW()
)

ON CONFLICT (id) DO NOTHING;


-- =============================================
-- MISSIONS 테이블 시드 데이터 (38개 미션)
-- =============================================

-- ── 전주 도깨비 (8 미션) ──

INSERT INTO missions (id, course_id, order_num, title, description, mission_type, location_name, latitude, longitude, answer, hint, lp_reward, is_boss, is_hidden)
VALUES

('m-jeonju-01', 'course-jeonju-dokkaebi', 1,
 '{"ko": "도깨비의 첫 번째 수수께끼", "ja": "トッケビの最初のなぞなぞ", "en": "The Dokkaebi''s First Riddle"}',
 '{"ko": "경기전에 도착해서 도깨비 전래동화의 첫 번째 퀴즈를 풀어보세요.", "ja": "慶基殿に到着して、トッケビ昔話の最初のクイズに挑戦しましょう。", "en": "Arrive at Gyeonggijeon and solve the first quiz about the Dokkaebi fairy tale."}',
 'quiz', '{"ko": "경기전", "ja": "慶基殿", "en": "Gyeonggijeon"}',
 35.8151, 127.1500,
 '{"ko": "노래", "ja": "歌", "en": "song"}',
 '{"ko": "도깨비가 나무꾼에게 원한 것은?", "ja": "トッケビが木こりに求めたものは？", "en": "What did the Dokkaebi want from the woodcutter?"}',
 100, false, false),

('m-jeonju-02', 'course-jeonju-dokkaebi', 2,
 '{"ko": "도깨비숲 탐험", "ja": "トッケビの森探検", "en": "Dokkaebi Forest Expedition"}',
 '{"ko": "전주 도깨비숲에서 도깨비 조형물을 찾아 인증샷을 찍으세요.", "ja": "全州トッケビの森でトッケビの像を見つけて記念撮影しましょう。", "en": "Find the Dokkaebi statue at Jeonju Dokkaebi Forest and take a photo."}',
 'photo', '{"ko": "전주 도깨비숲", "ja": "全州トッケビの森", "en": "Jeonju Dokkaebi Forest"}',
 35.8098, 127.1467,
 NULL,
 '{"ko": "완산칠봉 근처 숲놀이터를 찾아보세요", "ja": "完山七峰近くの森の遊び場を探してみましょう", "en": "Look for the forest playground near Wansan Chilbong"}',
 150, false, false),

('m-jeonju-03', 'course-jeonju-dokkaebi', 3,
 '{"ko": "벽화 속 도깨비 찾기", "ja": "壁画の中のトッケビ探し", "en": "Find the Dokkaebi in Murals"}',
 '{"ko": "자만벽화마을 골목을 걸으며 벽화 속에 숨겨진 도깨비를 찾아보세요.", "ja": "自慢壁画村の路地を歩きながら、壁画の中に隠れたトッケビを探しましょう。", "en": "Walk through Jaman Mural Village alleys and find the hidden Dokkaebi in the murals."}',
 'photo', '{"ko": "자만벽화마을", "ja": "自慢壁画村", "en": "Jaman Mural Village"}',
 35.8127, 127.1529,
 NULL,
 '{"ko": "골목 곳곳의 벽화를 자세히 살펴보세요", "ja": "路地のあちこちの壁画をよく見てみましょう", "en": "Look carefully at murals throughout the alleys"}',
 150, false, false),

('m-jeonju-04', 'course-jeonju-dokkaebi', 4,
 '{"ko": "오목대에서 전주를 내려다보다", "ja": "梧木台から全州を見下ろす", "en": "Overlook Jeonju from Omokdae"}',
 '{"ko": "오목대 전망대에 올라 전주 한옥마을 전경을 촬영하세요.", "ja": "梧木台展望台に登り、全州韓屋村の全景を撮影しましょう。", "en": "Climb Omokdae viewpoint and photograph the panoramic view of Jeonju Hanok Village."}',
 'photo', '{"ko": "오목대", "ja": "梧木台", "en": "Omokdae"}',
 35.8133, 127.1538,
 NULL,
 '{"ko": "한옥마을 뒤쪽 언덕 위로 올라가세요", "ja": "韓屋村の裏の丘の上に登りましょう", "en": "Go up the hill behind Hanok Village"}',
 100, false, false),

('m-jeonju-05', 'course-jeonju-dokkaebi', 5,
 '{"ko": "도깨비시장의 맛", "ja": "トッケビ市場の味", "en": "Taste of Dokkaebi Market"}',
 '{"ko": "남부시장에서 전주 대표 먹거리를 시식하고 퀴즈를 풀어보세요.", "ja": "南部市場で全州の代表的なグルメを試食してクイズに挑戦しましょう。", "en": "Try Jeonju''s signature street food at Nambu Market and solve the quiz."}',
 'quiz', '{"ko": "전주 남부시장", "ja": "全州南部市場", "en": "Jeonju Nambu Market"}',
 35.8107, 127.1479,
 '{"ko": "비빔밥", "ja": "ビビンバ", "en": "bibimbap"}',
 '{"ko": "전주를 대표하는 음식은?", "ja": "全州を代表する食べ物は？", "en": "What is Jeonju''s signature dish?"}',
 100, false, false),

('m-jeonju-06', 'course-jeonju-dokkaebi', 6,
 '{"ko": "한지의 비밀", "ja": "韓紙の秘密", "en": "Secret of Hanji"}',
 '{"ko": "전주한지박물관에서 한지에 대한 퀴즈를 풀어보세요.", "ja": "全州韓紙博物館で韓紙に関するクイズに挑戦しましょう。", "en": "Solve a quiz about Hanji (traditional Korean paper) at the Jeonju Hanji Museum."}',
 'quiz', '{"ko": "전주한지박물관", "ja": "全州韓紙博物館", "en": "Jeonju Hanji Museum"}',
 35.8143, 127.1521,
 '{"ko": "닥나무", "ja": "楮（こうぞ）", "en": "mulberry tree"}',
 '{"ko": "한지의 주원료가 되는 나무는?", "ja": "韓紙の主原料となる木は？", "en": "What tree is the main material for Hanji?"}',
 100, false, false),

('m-jeonju-07', 'course-jeonju-dokkaebi', 7,
 '{"ko": "한복과 성당", "ja": "韓服と聖堂", "en": "Hanbok and Cathedral"}',
 '{"ko": "한복을 입고 전동성당 앞에서 인증샷을 찍으세요.", "ja": "韓服を着て殿洞聖堂の前で記念撮影しましょう。", "en": "Wear a Hanbok and take a photo in front of Jeondong Cathedral."}',
 'photo', '{"ko": "전동성당", "ja": "殿洞聖堂", "en": "Jeondong Cathedral"}',
 35.8147, 127.1497,
 NULL,
 '{"ko": "한옥마을 입구 근처의 로마네스크 양식 성당입니다", "ja": "韓屋村入口近くのロマネスク様式の聖堂です", "en": "A Romanesque-style cathedral near the Hanok Village entrance"}',
 150, false, false),

('m-jeonju-08', 'course-jeonju-dokkaebi', 8,
 '{"ko": "도깨비방망이를 찾아라!", "ja": "トッケビの棒を探せ！", "en": "Find the Dokkaebi Club!"}',
 '{"ko": "전주향교에서 최종 보스 미션! 도깨비 전래동화에 대한 종합 퀴즈를 풀어보세요.", "ja": "全州郷校で最終ボスミッション！トッケビ昔話の総合クイズに挑戦しましょう。", "en": "Final boss mission at Jeonju Hyanggyo! Solve the comprehensive quiz about the Dokkaebi fairy tale."}',
 'quiz', '{"ko": "전주향교", "ja": "全州郷校", "en": "Jeonju Hyanggyo"}',
 35.8126, 127.1550,
 '{"ko": "방망이", "ja": "棒", "en": "club"}',
 '{"ko": "도깨비가 나무꾼에게 선물한 것은?", "ja": "トッケビが木こりに贈ったものは？", "en": "What did the Dokkaebi give the woodcutter?"}',
 300, true, false),


-- ── 통영 별주부전 (8 미션) ──

('m-tongyeong-01', 'course-tongyeong-byeoljubu', 1,
 '{"ko": "용왕의 부름", "ja": "龍王の呼び声", "en": "The Sea King''s Call"}',
 '{"ko": "강구안 관광안내소에서 별주부전 이야기의 첫 번째 퀴즈를 풀어보세요.", "ja": "カングアン観光案内所でピョルジュブ伝の最初のクイズに挑戦しましょう。", "en": "Solve the first quiz about the Byeoljubu tale at Ganggu-an tourist center."}',
 'quiz', '{"ko": "강구안", "ja": "カングアン", "en": "Ganggu-an Harbor"}',
 34.8422, 128.4231,
 '{"ko": "간", "ja": "肝", "en": "liver"}',
 '{"ko": "용왕이 토끼에게서 필요로 한 것은?", "ja": "龍王がウサギから必要としたものは？", "en": "What did the Sea King need from the rabbit?"}',
 100, false, false),

('m-tongyeong-02', 'course-tongyeong-byeoljubu', 2,
 '{"ko": "동피랑의 토끼와 자라", "ja": "東ピランのウサギとスッポン", "en": "Rabbit & Turtle of Dongpirang"}',
 '{"ko": "동피랑 벽화마을에서 토끼와 자라가 그려진 벽화를 찾아 인증샷을 찍으세요.", "ja": "東ピラン壁画村でウサギとスッポンが描かれた壁画を見つけて記念撮影しましょう。", "en": "Find murals depicting the rabbit and turtle at Dongpirang Mural Village and take a photo."}',
 'photo', '{"ko": "동피랑 벽화마을", "ja": "東ピラン壁画村", "en": "Dongpirang Mural Village"}',
 34.8438, 128.4258,
 NULL,
 '{"ko": "동피랑 골목 곳곳에 바다 동물 벽화가 있어요", "ja": "東ピランの路地のあちこちに海の動物の壁画があります", "en": "Look for sea animal murals throughout Dongpirang alleys"}',
 150, false, false),

('m-tongyeong-03', 'course-tongyeong-byeoljubu', 3,
 '{"ko": "용궁으로 가는 길", "ja": "龍宮への道", "en": "Path to the Dragon Palace"}',
 '{"ko": "통영 해저터널을 통과하며 용궁에 들어가는 기분을 느껴보세요. 터널 끝에서 GPS 체크인!", "ja": "統営海底トンネルを通り抜けながら龍宮に入る気分を味わいましょう。トンネルの出口でGPSチェックイン！", "en": "Walk through Tongyeong Undersea Tunnel and feel like you''re entering the Dragon Palace. GPS check-in at the tunnel exit!"}',
 'photo', '{"ko": "통영 해저터널", "ja": "統営海底トンネル", "en": "Tongyeong Undersea Tunnel"}',
 34.8396, 128.4194,
 NULL,
 '{"ko": "1931년 만들어진 동양 최초 해저터널입니다", "ja": "1931年に造られた東洋初の海底トンネルです", "en": "This is the first undersea tunnel in the East, built in 1931"}',
 150, false, false),

('m-tongyeong-04', 'course-tongyeong-byeoljubu', 4,
 '{"ko": "바다의 맛", "ja": "海の味", "en": "Taste of the Sea"}',
 '{"ko": "통영 중앙시장에서 충무김밥 또는 꿀빵을 시식하고 퀴즈를 풀어보세요.", "ja": "統営中央市場で忠武キンパまたはハニーブレッドを試食してクイズに挑戦しましょう。", "en": "Try Chungmu Gimbap or honey bread at Tongyeong Central Market and solve the quiz."}',
 'quiz', '{"ko": "통영 중앙시장", "ja": "統営中央市場", "en": "Tongyeong Central Market"}',
 34.8431, 128.4227,
 '{"ko": "충무김밥", "ja": "忠武キンパ", "en": "Chungmu Gimbap"}',
 '{"ko": "통영의 대표 음식은?", "ja": "統営の代表的な食べ物は？", "en": "What is Tongyeong''s signature food?"}',
 100, false, false),

('m-tongyeong-05', 'course-tongyeong-byeoljubu', 5,
 '{"ko": "서피랑 99계단", "ja": "西ピラン99段", "en": "Seobirang 99 Steps"}',
 '{"ko": "서피랑 99계단을 올라 꼭대기에서 강구안 전경을 촬영하세요.", "ja": "西ピラン99段を登り、頂上からカングアンの全景を撮影しましょう。", "en": "Climb the 99 steps of Seobirang and photograph the panoramic view of Ganggu-an from the top."}',
 'photo', '{"ko": "서피랑 99계단", "ja": "西ピラン99段", "en": "Seobirang 99 Steps"}',
 34.8445, 128.4198,
 NULL,
 '{"ko": "서피랑 정상의 서포루에서 통영 시내가 한눈에 보입니다", "ja": "西ピラン頂上の西浦楼から統営市内が一望できます", "en": "You can see all of Tongyeong from Seoporu at the top of Seobirang"}',
 150, false, false),

('m-tongyeong-06', 'course-tongyeong-byeoljubu', 6,
 '{"ko": "토끼가 날아오른 섬", "ja": "ウサギが飛び立った島", "en": "The Island Where the Rabbit Flew"}',
 '{"ko": "비토섬 토끼섬 트레일을 완주하고 포토를 찍으세요.", "ja": "ビト島のウサギ島トレイルを完走して写真を撮りましょう。", "en": "Complete the Bito Island Rabbit Island trail and take a photo."}',
 'photo', '{"ko": "비토섬 토끼섬", "ja": "ビト島ウサギ島", "en": "Bito Island - Rabbit Island"}',
 34.9135, 128.3254,
 NULL,
 '{"ko": "비토(飛兎)는 토끼가 날아오른 섬이라는 뜻이에요", "ja": "ビト（飛兎）はウサギが飛び立った島という意味です", "en": "Bito (飛兎) means the island where the rabbit flew away"}',
 200, false, false),

('m-tongyeong-07', 'course-tongyeong-byeoljubu', 7,
 '{"ko": "자라의 속임수", "ja": "スッポンの計略", "en": "The Turtle''s Trick"}',
 '{"ko": "거북섬에서 별주부전 관련 퀴즈를 풀어보세요.", "ja": "亀島でピョルジュブ伝に関するクイズに挑戦しましょう。", "en": "Solve a Byeoljubu tale quiz at Turtle Island."}',
 'quiz', '{"ko": "비토섬 거북섬", "ja": "ビト島亀島", "en": "Bito Island - Turtle Island"}',
 34.9128, 128.3248,
 '{"ko": "육지에 두고 왔다", "ja": "陸に置いてきた", "en": "left it on land"}',
 '{"ko": "토끼가 용궁에서 탈출한 방법은?", "ja": "ウサギが龍宮から脱出した方法は？", "en": "How did the rabbit escape from the Dragon Palace?"}',
 100, false, false),

('m-tongyeong-08', 'course-tongyeong-byeoljubu', 8,
 '{"ko": "용왕에게 보고하라!", "ja": "龍王に報告せよ！", "en": "Report to the Sea King!"}',
 '{"ko": "별주부전 테마파크에서 최종 보스 미션! 종합 퀴즈를 풀고 용왕에게 보고서를 작성하세요.", "ja": "ピョルジュブ伝テーマパークで最終ボスミッション！総合クイズを解いて龍王に報告書を作成しましょう。", "en": "Final boss mission at the Byeoljubu Theme Park! Solve the comprehensive quiz and write a report to the Sea King."}',
 'open', '{"ko": "별주부전 테마파크", "ja": "ピョルジュブ伝テーマパーク", "en": "Byeoljubu Theme Park"}',
 34.9140, 128.3260,
 NULL,
 '{"ko": "별주부전 전체 이야기를 떠올리며 자유롭게 작성하세요", "ja": "ピョルジュブ伝の全体の物語を思い出しながら自由に書きましょう", "en": "Recall the entire Byeoljubu story and write freely"}',
 300, true, false),


-- ── 천안 능소전 (7 미션) ──

('m-cheonan-01', 'course-cheonan-nungso', 1,
 '{"ko": "능소전의 시작", "ja": "ヌンソ伝の始まり", "en": "The Beginning of Nungso''s Tale"}',
 '{"ko": "천안삼거리공원 입구에서 능소전 이야기의 첫 번째 퀴즈를 풀어보세요.", "ja": "天安三叉路公園入口でヌンソ伝の最初のクイズに挑戦しましょう。", "en": "Solve the first Nungso tale quiz at the entrance of Cheonan Samgeori Park."}',
 'quiz', '{"ko": "천안삼거리공원 입구", "ja": "天安三叉路公園入口", "en": "Cheonan Samgeori Park Entrance"}',
 36.7978, 127.1522,
 '{"ko": "충주댁", "ja": "忠州屋の女将", "en": "the innkeeper Chungju-daek"}',
 '{"ko": "능소의 아버지가 능소를 맡긴 사람은?", "ja": "ヌンソの父がヌンソを預けた人は？", "en": "Who did Nungso''s father entrust her to?"}',
 100, false, false),

('m-cheonan-02', 'course-cheonan-nungso', 2,
 '{"ko": "능수버들 아래에서", "ja": "しだれ柳の下で", "en": "Beneath the Weeping Willow"}',
 '{"ko": "능소 조형물과 능수버들 길에서 인증샷을 찍으세요.", "ja": "ヌンソの像としだれ柳の道で記念撮影しましょう。", "en": "Take a photo with the Nungso statue along the weeping willow path."}',
 'photo', '{"ko": "능소 조형물 & 능수버들 길", "ja": "ヌンソ像 & しだれ柳の道", "en": "Nungso Statue & Willow Path"}',
 36.7982, 127.1518,
 NULL,
 '{"ko": "공원 안쪽의 능수버들 가로수길을 따라 걸어보세요", "ja": "公園内のしだれ柳の並木道を歩いてみましょう", "en": "Walk along the weeping willow tree-lined path inside the park"}',
 150, false, false),

('m-cheonan-03', 'course-cheonan-nungso', 3,
 '{"ko": "능소에게 편지 쓰기", "ja": "ヌンソへの手紙", "en": "Letter to Nungso"}',
 '{"ko": "능소각 정자에서 능소에게 보내는 짧은 편지를 작성하세요.", "ja": "ヌンソ閣の東屋でヌンソに送る短い手紙を書きましょう。", "en": "Write a short letter to Nungso at Nunso-gak pavilion."}',
 'open', '{"ko": "능소각", "ja": "ヌンソ閣", "en": "Nunso-gak Pavilion"}',
 36.7985, 127.1515,
 NULL,
 '{"ko": "기다림과 사랑에 대해 자유롭게 써보세요", "ja": "待つことと愛について自由に書いてみましょう", "en": "Write freely about waiting and love"}',
 200, false, false),

('m-cheonan-04', 'course-cheonan-nungso', 4,
 '{"ko": "박현수가 쓰러진 곳", "ja": "パク・ヒョンスが倒れた場所", "en": "Where Park Hyun-su Collapsed"}',
 '{"ko": "영남루 터에서 능소전 스토리 관련 퀴즈를 풀어보세요.", "ja": "嶺南楼跡でヌンソ伝のストーリーに関するクイズに挑戦しましょう。", "en": "Solve a Nungso tale quiz at the Yeongnam-ru site."}',
 'quiz', '{"ko": "영남루 터", "ja": "嶺南楼跡", "en": "Yeongnam-ru Site"}',
 36.7975, 127.1525,
 '{"ko": "과거시험", "ja": "科挙試験", "en": "civil service exam"}',
 '{"ko": "박현수가 천안을 지나가던 이유는?", "ja": "パク・ヒョンスが天安を通りかかった理由は？", "en": "Why was Park Hyun-su passing through Cheonan?"}',
 100, false, false),

('m-cheonan-05', 'course-cheonan-nungso', 5,
 '{"ko": "천안의 맛", "ja": "天安の味", "en": "Taste of Cheonan"}',
 '{"ko": "천안중앙시장에서 호두과자 또는 병천순대를 시식하고 퀴즈를 풀어보세요.", "ja": "天安中央市場でクルミ菓子または餅天スンデを試食してクイズに挑戦しましょう。", "en": "Try walnut cookies or Byeongcheon sundae at Cheonan Central Market and solve the quiz."}',
 'quiz', '{"ko": "천안중앙시장", "ja": "天安中央市場", "en": "Cheonan Central Market"}',
 36.8114, 127.1468,
 '{"ko": "호두과자", "ja": "クルミ菓子", "en": "walnut cookies"}',
 '{"ko": "천안의 대표 간식은?", "ja": "天安の代表的なおやつは？", "en": "What is Cheonan''s signature snack?"}',
 100, false, false),

('m-cheonan-06', 'course-cheonan-nungso', 6,
 '{"ko": "봉서산에서 바라본 천안", "ja": "鳳棲山から見た天安", "en": "Cheonan from Bongseosan"}',
 '{"ko": "봉서산 전망대에서 천안 시내 전경을 촬영하세요.", "ja": "鳳棲山展望台から天安市内の全景を撮影しましょう。", "en": "Photograph the panoramic view of Cheonan from Bongseosan viewpoint."}',
 'photo', '{"ko": "봉서산 전망대", "ja": "鳳棲山展望台", "en": "Bongseosan Viewpoint"}',
 36.8048, 127.1445,
 NULL,
 '{"ko": "공원 뒤쪽 산책로를 따라 올라가면 전망대가 있어요", "ja": "公園裏の散策路を登ると展望台があります", "en": "Follow the walking trail behind the park to find the viewpoint"}',
 150, false, false),

('m-cheonan-07', 'course-cheonan-nungso', 7,
 '{"ko": "흥타령을 완성하라!", "ja": "フンタリョンを完成させよ！", "en": "Complete the Heungtaryeong!"}',
 '{"ko": "흥타령 거리에서 최종 보스 미션! 흥타령 가사 빈칸 채우기와 종합 퀴즈를 풀어보세요.", "ja": "フンタリョン通りで最終ボスミッション！フンタリョンの歌詞の穴埋めと総合クイズに挑戦しましょう。", "en": "Final boss mission on Heungtaryeong Street! Fill in the blanks of the Heungtaryeong lyrics and solve the comprehensive quiz."}',
 'quiz', '{"ko": "흥타령 거리", "ja": "フンタリョン通り", "en": "Heungtaryeong Street"}',
 36.8020, 127.1500,
 '{"ko": "흥", "ja": "フン", "en": "heung"}',
 '{"ko": "천안삼거리 ○~ 에서 빈칸에 들어갈 글자는?", "ja": "天安三叉路○〜の空欄に入る文字は？", "en": "What letter fills the blank in Cheonan Samgeori ○~?"}',
 300, true, false),


-- ── 용인 동화 (8 미션) ──

('m-yongin-01', 'course-yongin-fairytale', 1,
 '{"ko": "동화의 문을 열다", "ja": "童話の扉を開く", "en": "Open the Door to Fairy Tales"}',
 '{"ko": "한국민속촌 입구에서 한국 전래동화 5개의 이름을 맞춰보세요.", "ja": "韓国民俗村入口で韓国昔話5作品の名前を当てましょう。", "en": "Name five Korean fairy tales at the Korean Folk Village entrance."}',
 'quiz', '{"ko": "한국민속촌 정문", "ja": "韓国民俗村正門", "en": "Korean Folk Village Main Gate"}',
 37.2590, 127.1185,
 '{"ko": "콩쥐팥쥐, 흥부놀부, 혹부리영감, 선녀와 나무꾼, 금도끼 은도끼", "ja": "コンジュパッジュ、フンブノルブ、コブトリ爺さん、仙女と木こり、金の斧銀の斧", "en": "Kongjwi Patjwi, Heungbu Nolbu, Old Man Wart, Fairy and Woodcutter, Gold Axe Silver Axe"}',
 '{"ko": "이 코스에서 만나게 될 다섯 편의 동화 이름을 떠올려보세요", "ja": "このコースで出会う5つの童話の名前を思い出しましょう", "en": "Think of the five fairy tales you''ll encounter on this course"}',
 100, false, false),

('m-yongin-02', 'course-yongin-fairytale', 2,
 '{"ko": "콩쥐가 되어보기", "ja": "コンジュになってみよう", "en": "Become Kongjwi"}',
 '{"ko": "콩쥐팥쥐 포토존에서 한복을 입고 인증샷을 찍으세요.", "ja": "コンジュパッジュフォトゾーンで韓服を着て記念撮影しましょう。", "en": "Wear a Hanbok and take a photo at the Kongjwi Patjwi photo zone."}',
 'photo', '{"ko": "콩쥐팥쥐 포토존", "ja": "コンジュパッジュフォトゾーン", "en": "Kongjwi Patjwi Photo Zone"}',
 37.2578, 127.1192,
 NULL,
 '{"ko": "동화마을 구역에 포토존이 있어요", "ja": "童話村エリアにフォトゾーンがあります", "en": "The photo zone is in the fairy tale village area"}',
 150, false, false),

('m-yongin-03', 'course-yongin-fairytale', 3,
 '{"ko": "흥부의 박 터뜨리기", "ja": "フンブのひょうたん割り", "en": "Heungbu''s Gourd Smash"}',
 '{"ko": "흥부놀부 체험존에서 박 터뜨리기 포토를 찍거나 퀴즈를 풀어보세요.", "ja": "フンブ・ノルブ体験ゾーンでひょうたん割りの写真を撮るかクイズに挑戦しましょう。", "en": "Take a gourd-smashing photo or solve a quiz at the Heungbu Nolbu experience zone."}',
 'photo', '{"ko": "흥부놀부 체험존", "ja": "フンブ・ノルブ体験ゾーン", "en": "Heungbu Nolbu Experience Zone"}',
 37.2572, 127.1198,
 NULL,
 '{"ko": "흥부가 박을 타면 보물이, 놀부가 박을 타면...?", "ja": "フンブがひょうたんを割ると宝が、ノルブが割ると...？", "en": "When Heungbu opens a gourd, treasure comes out. When Nolbu opens one...?"}',
 150, false, false),

('m-yongin-04', 'course-yongin-fairytale', 4,
 '{"ko": "도깨비가 좋아하는 것", "ja": "トッケビの好きなもの", "en": "What the Dokkaebi Loves"}',
 '{"ko": "혹부리영감 도깨비방망이 포인트에서 퀴즈를 풀어보세요.", "ja": "コブトリ爺さんトッケビの棒ポイントでクイズに挑戦しましょう。", "en": "Solve a quiz at the Old Man Wart Dokkaebi club point."}',
 'quiz', '{"ko": "혹부리영감 포인트", "ja": "コブトリ爺さんポイント", "en": "Old Man Wart Point"}',
 37.2565, 127.1205,
 '{"ko": "노래", "ja": "歌", "en": "singing"}',
 '{"ko": "혹부리영감이 도깨비에게 해준 것은?", "ja": "コブトリ爺さんがトッケビにしてあげたことは？", "en": "What did Old Man Wart do for the Dokkaebi?"}',
 100, false, false),

('m-yongin-05', 'course-yongin-fairytale', 5,
 '{"ko": "선녀의 깃옷을 찾아라", "ja": "仙女の羽衣を探せ", "en": "Find the Fairy''s Robe"}',
 '{"ko": "선녀와 나무꾼 연못 주변에서 숨겨진 깃옷 포인트를 찾아보세요.", "ja": "仙女と木こりの池の周りで隠された羽衣ポイントを探しましょう。", "en": "Find the hidden feathered robe point around the Fairy and Woodcutter pond."}',
 'photo', '{"ko": "선녀와 나무꾼 연못", "ja": "仙女と木こりの池", "en": "Fairy & Woodcutter Pond"}',
 37.2558, 127.1210,
 NULL,
 '{"ko": "연못 주변을 천천히 살펴보세요", "ja": "池の周りをゆっくり見てみましょう", "en": "Look carefully around the pond"}',
 200, false, true),

('m-yongin-06', 'course-yongin-fairytale', 6,
 '{"ko": "달고나의 추억", "ja": "タルゴナの思い出", "en": "Dalgona Memories"}',
 '{"ko": "전통시장 거리에서 달고나를 만들고 전통 음식 퀴즈를 풀어보세요.", "ja": "伝統市場通りでタルゴナを作り、伝統料理クイズに挑戦しましょう。", "en": "Make dalgona at the traditional market street and solve a traditional food quiz."}',
 'quiz', '{"ko": "전통시장 거리", "ja": "伝統市場通り", "en": "Traditional Market Street"}',
 37.2582, 127.1175,
 '{"ko": "달고나", "ja": "タルゴナ", "en": "dalgona"}',
 '{"ko": "설탕을 녹여 만드는 한국의 전통 간식은?", "ja": "砂糖を溶かして作る韓国の伝統おやつは？", "en": "What Korean traditional snack is made by melting sugar?"}',
 100, false, false),

('m-yongin-07', 'course-yongin-fairytale', 7,
 '{"ko": "풍물놀이의 박자", "ja": "プンムルノリのリズム", "en": "Rhythm of Pungmul"}',
 '{"ko": "풍물놀이 마당에서 공연을 관람하고 악기 이름 퀴즈를 풀어보세요.", "ja": "プンムルノリ広場で公演を観覧し、楽器の名前クイズに挑戦しましょう。", "en": "Watch a performance at the Pungmul yard and solve a musical instrument name quiz."}',
 'quiz', '{"ko": "풍물놀이 마당", "ja": "プンムルノリ広場", "en": "Pungmul Performance Yard"}',
 37.2575, 127.1168,
 '{"ko": "꽹과리, 장구, 북, 징", "ja": "ケンガリ、チャング、プク、チン", "en": "kkwaenggwari, janggu, buk, jing"}',
 '{"ko": "사물놀이에 쓰이는 4가지 악기는?", "ja": "サムルノリに使われる4つの楽器は？", "en": "What are the 4 instruments used in Samulnori?"}',
 100, false, false),

('m-yongin-08', 'course-yongin-fairytale', 8,
 '{"ko": "산신령의 시험", "ja": "山の神の試練", "en": "The Mountain Spirit''s Test"}',
 '{"ko": "금도끼 은도끼 산신령 동상 앞에서 최종 보스 미션! 종합 퀴즈를 풀어보세요.", "ja": "金の斧銀の斧の山の神の像の前で最終ボスミッション！総合クイズに挑戦しましょう。", "en": "Final boss mission at the Gold Axe Silver Axe mountain spirit statue! Solve the comprehensive quiz."}',
 'quiz', '{"ko": "산신령 동상", "ja": "山の神像", "en": "Mountain Spirit Statue"}',
 37.2560, 127.1180,
 '{"ko": "쇠도끼", "ja": "鉄の斧", "en": "iron axe"}',
 '{"ko": "정직한 나무꾼이 고른 도끼는?", "ja": "正直な木こりが選んだ斧は？", "en": "Which axe did the honest woodcutter choose?"}',
 300, true, false),


-- ── 이천 선녀와 나무꾼 (7 미션) ──

('m-icheon-01', 'course-icheon-fairy', 1,
 '{"ko": "사슴의 보은", "ja": "鹿の恩返し", "en": "The Deer''s Gratitude"}',
 '{"ko": "효양산 입구 안내판에서 선녀와 나무꾼 이야기의 첫 번째 퀴즈를 풀어보세요.", "ja": "ヒョヤン山入口の案内板で仙女と木こりの最初のクイズに挑戦しましょう。", "en": "Solve the first Fairy and Woodcutter quiz at the Hyoyangsan entrance sign."}',
 'quiz', '{"ko": "효양산 입구", "ja": "ヒョヤン山入口", "en": "Hyoyangsan Entrance"}',
 37.2745, 127.4352,
 '{"ko": "연못", "ja": "池", "en": "pond"}',
 '{"ko": "사슴이 나무꾼에게 알려준 장소는?", "ja": "鹿が木こりに教えた場所は？", "en": "What place did the deer tell the woodcutter about?"}',
 100, false, false),

('m-icheon-02', 'course-icheon-fairy', 2,
 '{"ko": "선녀의 연못", "ja": "仙女の池", "en": "The Fairy''s Pond"}',
 '{"ko": "효양산 선녀 연못 터에서 인증샷을 찍고 날개옷 포인트를 찾아보세요.", "ja": "ヒョヤン山の仙女の池跡で記念撮影し、羽衣ポイントを探しましょう。", "en": "Take a photo at the fairy pond site on Hyoyangsan and look for the feathered robe point."}',
 'photo', '{"ko": "선녀 연못 터", "ja": "仙女の池跡", "en": "Fairy Pond Site"}',
 37.2760, 127.4368,
 NULL,
 '{"ko": "효양산 중턱에 연못 터가 있어요", "ja": "ヒョヤン山の中腹に池の跡があります", "en": "The pond site is on the middle slope of Hyoyangsan"}',
 200, false, false),

('m-icheon-03', 'course-icheon-fairy', 3,
 '{"ko": "삼형제바위의 비밀", "ja": "三兄弟岩の秘密", "en": "Secret of the Three Brothers Rock"}',
 '{"ko": "설봉산 삼형제바위에서 설화 관련 퀴즈를 풀어보세요.", "ja": "雪峰山三兄弟岩で説話に関するクイズに挑戦しましょう。", "en": "Solve a folklore quiz at the Three Brothers Rock on Seolbongsan."}',
 'quiz', '{"ko": "설봉산 삼형제바위", "ja": "雪峰山三兄弟岩", "en": "Seolbongsan Three Brothers Rock"}',
 37.2698, 127.4401,
 '{"ko": "세 형제", "ja": "三兄弟", "en": "three brothers"}',
 '{"ko": "삼형제바위 설화에서 바위로 변한 것은?", "ja": "三兄弟岩の説話で岩に変わったのは？", "en": "What turned into rocks in the Three Brothers legend?"}',
 100, false, false),

('m-icheon-04', 'course-icheon-fairy', 4,
 '{"ko": "설봉호의 풍경", "ja": "雪峰湖の風景", "en": "Scenery of Seolbongho"}',
 '{"ko": "설봉호 수변공원에서 경치를 감상하고 포토를 찍으세요.", "ja": "雪峰湖水辺公園で景色を楽しみ写真を撮りましょう。", "en": "Enjoy the scenery at Seolbongho lakeside park and take a photo."}',
 'photo', '{"ko": "설봉호 수변공원", "ja": "雪峰湖水辺公園", "en": "Seolbongho Lakeside Park"}',
 37.2715, 127.4385,
 NULL,
 '{"ko": "설봉공원 내 호수 주변을 산책해보세요", "ja": "雪峰公園内の湖の周りを散歩してみましょう", "en": "Take a walk around the lake in Seolbong Park"}',
 100, false, false),

('m-icheon-05', 'course-icheon-fairy', 5,
 '{"ko": "도자기의 고장", "ja": "陶磁器の里", "en": "Home of Ceramics"}',
 '{"ko": "이천 도예마을에서 도자기 관련 퀴즈를 풀어보세요.", "ja": "利川陶芸村で陶磁器に関するクイズに挑戦しましょう。", "en": "Solve a ceramics quiz at Icheon Pottery Village."}',
 'quiz', '{"ko": "이천 도예마을", "ja": "利川陶芸村", "en": "Icheon Pottery Village"}',
 37.2631, 127.4512,
 '{"ko": "청자", "ja": "青磁", "en": "celadon"}',
 '{"ko": "고려시대를 대표하는 도자기는?", "ja": "高麗時代を代表する陶磁器は？", "en": "What type of pottery represents the Goryeo Dynasty?"}',
 100, false, false),

('m-icheon-06', 'course-icheon-fairy', 6,
 '{"ko": "이천 쌀밥의 맛", "ja": "利川ご飯の味", "en": "Taste of Icheon Rice"}',
 '{"ko": "이천 쌀밥거리에서 쌀밥 정식을 시식하고 재료 맞추기 퀴즈를 풀어보세요.", "ja": "利川ご飯通りでご飯定食を試食して食材当てクイズに挑戦しましょう。", "en": "Try Icheon rice set meal on Rice Street and solve a food ingredient quiz."}',
 'quiz', '{"ko": "이천 쌀밥거리", "ja": "利川ご飯通り", "en": "Icheon Rice Street"}',
 37.2789, 127.4345,
 '{"ko": "돌솥밥", "ja": "石焼きご飯", "en": "stone pot rice"}',
 '{"ko": "이천 쌀밥이 유명한 조리 방식은?", "ja": "利川ご飯が有名な調理法は？", "en": "What cooking method is Icheon rice famous for?"}',
 100, false, false),

('m-icheon-07', 'course-icheon-fairy', 7,
 '{"ko": "반룡송의 약속", "ja": "盤龍松の約束", "en": "Promise of the Banyongsong"}',
 '{"ko": "500년 된 소나무 반룡송 앞에서 최종 보스 미션! 나무꾼이 약속을 지켰다면 어떻게 되었을까? 자유롭게 답변하세요.", "ja": "樹齢500年の松・盤龍松の前で最終ボスミッション！木こりが約束を守っていたらどうなっていたでしょう？自由に答えてください。", "en": "Final boss mission at the 500-year-old Banyongsong pine! What would have happened if the woodcutter had kept his promise? Answer freely."}',
 'open', '{"ko": "반룡송", "ja": "盤龍松", "en": "Banyongsong Pine Tree"}',
 37.3012, 127.4890,
 NULL,
 '{"ko": "사슴이 나무꾼에게 한 충고를 떠올려보세요", "ja": "鹿が木こりにした忠告を思い出しましょう", "en": "Recall the advice the deer gave the woodcutter"}',
 300, true, false)

ON CONFLICT (id) DO NOTHING;
