const CITY_NAMES = ['서울', '부산', '제주', '전주', '경주', '통영', '천안', '용인', '이천']

export const KOREAN_FOOD_MAP: Record<string, string> = {
  // ── 밥·솥밥·덮밥 ──────────────────────────────────────────────────
  '비빔밥': 'bibimbap korean mixed rice bowl',
  '전주비빔밥': 'jeonju bibimbap korean rice bowl vegetables',
  '산채비빔밥': 'sanchaebibimbap wild vegetable bibimbap korean',
  '광덕산 산채비빔밥': 'mountain wild vegetable bibimbap cheonan korean',
  '육회비빔밥': 'yukhoe bibimbap raw beef rice bowl korean',
  '한우 육회비빔밥': 'hanwoo yukhoe bibimbap wagyu beef tartare rice',
  '멍게비빔밥': 'bibimbap korean rice bowl sea squirt',
  '꼬막비빔밥': 'cockle bibimbap korean rice bowl',
  '피꼬막': 'pikomak korean cockle steamed spicy',
  '육회': 'yukhoe korean beef tartare raw',
  '감자옹심이': 'gamja ongsimi potato dumpling soup korean',
  '용인 돌솥비빔밥': 'dolsot bibimbap stone pot rice bowl yongin',
  '솥밥': 'sotbap korean stone pot rice',
  '이천 쌀밥 정식': 'icheon white rice set meal korean',
  '쌀밥 정식': 'korean rice set meal',
  '오곡밥': 'ogokbap five grain rice korean',
  '연잎밥 정식': 'lotus leaf rice korean traditional',
  '곤드레밥': 'gondeure rice korean mountain herb',
  '용인 묵밥': 'mukbap acorn jelly rice soup yongin',

  // ── 김밥·주먹밥 ───────────────────────────────────────────────────
  '충무김밥': 'chungmu gimbap spicy rice roll korean',
  '교리김밥': 'gyori gimbap gyeongju rice roll',
  '광장시장 마약김밥': 'mayak gimbap mini rice roll korean market',

  // ── 국·탕·찌개 ───────────────────────────────────────────────────
  '설렁탕': 'seolleongtang ox bone soup korean milky',
  '용인 설렁탕': 'seolleongtang ox bone soup yongin korean',
  '갈비탕': 'galbitang short rib soup korean',
  '이천 갈비탕': 'galbitang short rib soup icheon korean',
  '천안 갈비탕': 'galbitang short rib soup cheonan korean',
  '감자탕': 'gamjatang pork spine potato stew korean',
  '삼계탕': 'samgyetang ginseng chicken soup korean',
  '용인 한방삼계탕': 'herbal ginseng chicken soup yongin korean',
  '순두부찌개': 'sundubu jjigae soft tofu stew korean',
  '용인 순두부찌개': 'sundubu jjigae soft tofu stew yongin',
  '김치찌개': 'kimchi jjigae stew korean',
  '된장찌개': 'doenjang jjigae soybean paste stew korean',
  '서울 된장찌개': 'doenjang jjigae soybean paste stew korean seoul',
  '경주 된장찌개': 'doenjang jjigae soybean stew gyeongju korean',
  '된장찌개 한상': 'doenjang jjigae full table set korean',
  '청국장': 'cheonggukjang fermented soybean stew korean',
  '청국장찌개': 'cheonggukjang jjigae fermented soybean stew',
  '천안 청국장찌개': 'cheonggukjang fermented soybean stew cheonan',
  '청국장정식': 'cheonggukjang jjigae set meal korean',
  '부대찌개': 'budae jjigae army stew sausage korean',
  '두부전골': 'dubu jeongol tofu hot pot korean',
  '용인 두부전골': 'dubu jeongol tofu hot pot yongin korean',
  '버섯전골': 'mushroom hot pot korean',
  '용인 버섯전골': 'mushroom hot pot yongin korean',
  '능이버섯샤브샤브': 'korean mushroom shabu hot pot',
  '유부전골': 'yubu jeongol tofu puff hot pot korean',
  '육개장': 'yukgaejang spicy shredded beef soup',
  '제주 고사리 육개장': 'gosari bracken fern spicy beef soup jeju',
  '곰탕': 'gomtang korean ox bone soup clear',
  '용인 양지곰탕': 'yangji brisket beef bone soup yongin',
  '순대국밥': 'sundae gukbap blood sausage rice soup korean',
  '순대국': 'sundae guk blood sausage soup korean',
  '콩나물국밥': 'kongnamul gukbap bean sprout rice soup',
  '천안 콩나물국밥': 'kongnamul gukbap bean sprout rice soup cheonan',
  '돼지국밥': 'pork rice soup korean busan',
  '해장국': 'haejangguk hangover soup korean',
  '경주 해장국': 'haejangguk hangover soup gyeongju korean',
  '소머리국밥': 'ox head soup rice korean',
  '대구탕': 'daegu tang cod fish soup korean',
  '통영 대구탕': 'daegu tang cod fish soup korean tongyeong',
  '복어탕': 'blowfish soup korean',
  '통영 굴국밥': 'oyster rice soup korean tongyeong',
  '성게미역국': 'sea urchin seaweed soup jeju korean',
  '도다리쑥국': 'flounder mugwort soup korean spring',
  '몸국': 'momguk seaweed pork soup jeju traditional',
  '제주 보말죽': 'bomal juk sea snail porridge jeju',
  '제주 접짝뼈국': 'pork back bone soup jeju korean',
  '해물뚝배기': 'haemul ttukbaegi seafood clay pot korean',
  '제주 해물뚝배기': 'haemul ttukbaegi seafood clay pot jeju',
  '제주 전복뚝배기': 'abalone clay pot soup jeju korean',
  '해물탕': 'haemul tang spicy seafood stew korean',
  '통영 해물탕': 'haemul tang spicy seafood stew tongyeong',
  '용인 해물탕': 'haemul tang spicy seafood stew yongin',
  '해물짬뽕': 'haemul jjamppong spicy seafood noodle soup',
  '통영 물메기탕': 'water catfish soup korean tongyeong',
  '통영 홍합탕': 'mussel soup korean tongyeong',
  '통영 해물잡탕': 'mixed seafood stew korean tongyeong',
  '오모가리탕': 'freshwater fish soup korean',
  '빠가사리 매운탕': 'catfish spicy stew korean freshwater',
  '닭한마리': 'dak hanmari whole chicken soup korean',
  '민속촌 장터국밥': 'jangteor gukbap market rice soup folk village',
  '시락국': 'sirak guk dried vegetable soup gyeongju korean',
  '빼때기죽': 'bbaettaegi juk dried sweet potato porridge jeju',

  // ── 고기구이·찜·볶음 ──────────────────────────────────────────────
  '삼겹살': 'samgyeopsal pork belly korean bbq grill',
  '볏짚 삼겹살': 'straw smoked pork belly korean',
  '흑돼지 구이': 'black pork belly jeju korean bbq',
  '용인 흑돼지구이': 'black pork belly grilled yongin korean',
  '천안 흑돼지구이': 'black pork belly grilled cheonan korean',
  '제주 흑돼지 김치볶음': 'black pork kimchi stir-fry jeju korean',
  '갈비': 'galbi korean bbq short ribs grilled',
  '불고기': 'bulgogi korean marinated grilled beef',
  '한우불고기': 'hanwoo bulgogi korean wagyu beef grilled',
  '한우 구이': 'hanwoo gui korean wagyu grilled beef',
  '용인 한우 구이': 'hanwoo korean wagyu beef grilled yongin',
  '이천 한우 구이': 'hanwoo korean wagyu beef grilled icheon',
  '서울 소갈비': 'sogalbi beef short rib korean seoul grilled',
  '떡갈비': 'tteokgalbi korean minced rib patty grilled',
  '전주 떡갈비': 'tteokgalbi jeonju korean meat patty grilled',
  '경주 떡갈비': 'tteokgalbi meat patty grilled gyeongju korean',
  '도자기불고기': 'bulgogi ceramic pot korean',
  '안동찜닭': 'andong jjimdak braised chicken soy sauce',
  '천안 숯불 닭갈비': 'charcoal grilled spicy chicken cheonan korean',
  '용인 처인닭갈비': 'spicy chicken stir-fry yongin korean',
  '용인 매운갈비찜': 'spicy braised short ribs yongin korean',
  '매운돼지갈비': 'spicy pork ribs korean',
  '제육볶음': 'jeyuk bokkeum spicy pork stir-fry korean',
  '낙지볶음': 'nakji bokkeum spicy stir-fried octopus',
  '오징어볶음': 'ojingeo bokkeum spicy squid stir-fry',
  '낙곱새': 'nakgopsae octopus tripe shrimp spicy korean',
  '곱창구이': 'gopchang grilled intestines korean bbq',
  '양곱창': 'yang gopchang beef tripe bbq korean',
  '양꼬치': 'yangkkochi grilled lamb skewer korean bbq',
  '곰장어구이': 'conger eel grilled korean bbq',

  // ── 생선·해산물 ───────────────────────────────────────────────────
  '장어구이': 'jangeo gui grilled eel korean',
  '장어구이정식': 'jangeo gui grilled eel set meal korean',
  '통영 장어구이': 'jangeo gui grilled eel korean tongyeong',
  '아구찜': 'agujjim spicy monkfish stew korean',
  '갈치조림': 'galchi jorim braised hairtail fish korean',
  '갈치구이': 'galchi hairtail fish grilled korean',
  '통영 갈치구이': 'galchi hairtail fish grilled korean tongyeong',
  '제주 갈치구이': 'galchi hairtail fish grilled jeju korean',
  '제주 옥돔구이': 'okdom red tilefish grilled jeju korean',
  '생선구이': 'grilled fish korean traditional',
  '미더덕찜': 'mideodeok jjim sea squirt steamed korean',
  '활어회': 'hwal eo hoe fresh raw fish sashimi korean',
  '멸치회무침': 'myeolchi hoe muchim anchovy salad Korean',
  '학꽁치 회': 'halfbeak sashimi korean',
  '한우 물회': 'mulhoe cold spicy raw fish soup korean',
  '제주 자리물회': 'jari damselfish cold raw soup jeju',
  '제주 한치물회': 'squid cold raw soup jeju korean',
  '물회': 'mulhoe cold raw fish soup korean',
  '전복죽': 'jeonbokjuk abalone porridge korean',
  '통영 굴밥': 'gulmam oyster rice korean tongyeong',
  '통영 전복구이': 'grilled abalone korean tongyeong',
  '굴전': 'guljeon oyster pancake fried korean',
  '조개구이': 'jokbal shellfish grilled korean bbq',
  '통영 생선회 정식': 'sashimi set meal korean tongyeong',
  '다찌 해산물': 'japanese style mixed seafood platter korean',
  '간장게장': 'ganjang gejang soy marinated raw crab korean',
  '보리굴비': 'bori gulbi barley dried yellow corvina fish',
  '용인 보리굴비정식': 'dried yellow corvina barley rice set yongin',
  '돔베고기': 'dombe gogi jeju boiled pork traditional',
  '제주 고사리볶음': 'gosari bokkeum bracken fern stir-fry jeju',

  // ── 면류 ──────────────────────────────────────────────────────────
  '칼국수': 'kalguksu knife-cut noodle soup korean',
  '전주식 칼국수': 'jeonju style kalguksu knife-cut noodle soup',
  '서울 칼국수': 'kalguksu knife-cut noodle soup korean seoul',
  '천안 칼국수': 'kalguksu knife-cut noodle soup cheonan',
  '통영 바지락칼국수': 'clam kalguksu noodle soup korean tongyeong',
  '보말칼국수': 'sea snail kalguksu noodle soup jeju',
  '냉면': 'naengmyeon cold noodles korean',
  '막국수': 'makguksu buckwheat noodles korean',
  '이천 막국수': 'makguksu buckwheat noodles icheon korean',
  '수지 막국수': 'makguksu buckwheat noodles yongin korean',
  '꿩메밀국수': 'pheasant buckwheat noodles korean',
  '보리국수': 'barley noodle soup korean',
  '고기국수': 'gogi guksu pork noodle soup jeju korean',
  '콩국수': 'konguksu cold soybean noodles summer korean',
  '수제비': 'sujebi hand-torn noodle soup korean',
  '천안 수제비': 'sujebi hand-torn noodle dumpling soup cheonan',
  '밀면': 'milmyeon cold wheat noodles busan korean',
  '경주 밀면': 'milmyeon wheat noodles gyeongju korean',
  '메밀전병': 'memil jeonbyeong buckwheat crepe korean',
  '용인 메밀전병': 'buckwheat crepe yongin korean',
  '물짜장': 'mul jjajangmyeon watery black bean sauce noodles',
  '라볶이': 'rabokki ramen tteokbokki spicy korean street food',
  '해물파전': 'haemul pajeon seafood pancake korean',
  '천안 해물파전': 'haemul pajeon seafood pancake cheonan',

  // ── 전·부침 ───────────────────────────────────────────────────────
  '파전': 'pajeon green onion pancake korean',
  '민속촌 파전': 'pajeon scallion pancake folk village yongin',
  '광장시장 빈대떡': 'bindaetteok mung bean pancake korean market',
  '빈대떡': 'bindaetteok mung bean pancake korean',
  '녹두전': 'nokdujeon mung bean pancake korean',
  '김치전': 'kimchi pancake korean jeon',
  '빙떡': 'bingtteok jeju savory rolled pancake',

  // ── 뼈·내장·곱창 ──────────────────────────────────────────────────
  '피순대와 순대국밥': 'blood sausage sundae gukbap rice soup korean',
  '병천순대': 'byeongcheon sundae blood sausage korean cheonan',
  '백암순대': 'baekam sundae blood sausage korean',
  '우짜': 'ujja spicy pork rice cake busan korean',

  // ── 정식·한상·세트 ────────────────────────────────────────────────
  '한정식': 'hanjeongsik korean full course meal',
  '전주 한정식': 'hanjeongsik jeonju korean full course meal',
  '경주 한정식': 'hanjeongsik full course meal gyeongju',
  '용인 산채정식': 'mountain vegetable set meal yongin korean',
  '천안 보리밥정식': 'barley rice set meal cheonan korean',
  '임금님 수라상': 'korean royal court cuisine traditional',
  '구절판': 'gujeolpan nine-section platter korean royal',
  '쌈밥 정식': 'ssambap lettuce wrap rice korean',

  // ── 조림·무침·기타 반찬 ──────────────────────────────────────────
  '도토리묵 무침': 'dotori muk acorn jelly salad korean',
  '잡채': 'japchae glass noodles vegetables korean',
  '비빔당면': 'bibim dangmyeon spicy cold glass noodles',
  '천안 두부김치': 'dubu kimchi tofu stir-fry cheonan korean',
  '천안 우렁된장': 'water snail doenjang paste stew cheonan',

  // ── 보쌈·족발·수육 ───────────────────────────────────────────────
  '보쌈': 'bossam steamed pork wrap korean',
  '천안 보쌈': 'bossam steamed pork wrap cheonan korean',
  '족발': 'jokbal braised pork trotters korean',
  '천안 족발': 'jokbal braised pork trotters cheonan korean',
  '냉채족발': 'cold pork trotter salad korean',

  // ── 홍어·특산 ─────────────────────────────────────────────────────
  '천안 홍어삼합': 'hongeo samhap fermented skate cheonan korean',

  // ── 만두·떡볶이·분식 ──────────────────────────────────────────────
  '떡볶이': 'tteokbokki spicy rice cake korean street food',
  '물떡': 'mulddeok steamed glutinous rice cake',
  '어묵': 'eomuk fish cake korean',
  '어묵탕': 'eomuk tang fish cake soup skewer korean',
  '옹기만두': 'ongi mandu ceramic steamed dumpling korean',
  '누룽지 백숙': 'scorched rice chicken soup korean',

  // ── 거리음식 ──────────────────────────────────────────────────────
  '씨앗호떡': 'ssiat hotteok seed-filled pancake busan',
  '서울 호떡': 'hotteok korean sweet pancake street food',
  '길거리 토스트': 'korean street toast egg sandwich',
  '한강 라면': 'ramyeon korean instant noodle han river',
  '치맥': 'chimaek korean fried chicken beer combo',
  '바게트 버거': 'baguette burger tongyeong street food korean',
  '뚜쥬루 앙버터빵': 'anpan butter bread tongyeong korean specialty',

  // ── 떡·한과·디저트 ───────────────────────────────────────────────
  '오메기떡': 'omegi tteok jeju mochi rice cake',
  '약과': 'yakgwa korean honey cookie traditional',
  '한과': 'hangwa korean traditional confectionery sweets',
  '이천 한과': 'hangwa korean traditional confectionery icheon',
  '황남빵': 'hwangnam bread gyeongju korean walnut',
  '호두과자': 'hoduguaja walnut shaped cookie cheonan',
  '꿀빵': 'kkul bbang honey bread tongyeong korean',
  '밤엿': 'chestnut taffy candy korean traditional',
  '찹쌀떡': 'chapssal tteok glutinous rice cake korean',
  '찰보리빵': 'chalboribbbang glutinous barley bread cheonan',
  '천안 막걸리빵': 'makgeolli rice wine bread cheonan korean',
  '떡국': 'tteokguk rice cake soup korean new year',
  '복숭아빵': 'peach shaped bread korean pastry sweet',
  '감귤 파운드 케이크': 'citrus orange pound cake korean jeju',
  '한라봉 디저트': 'hallabong tangerine dessert jeju korean',
  '식혜': 'sikhye korean sweet rice punch drink',
  '수제 초코파이': 'homemade chocolate pie korean',
  '생과일 모찌': 'fresh fruit daifuku mochi korean',
  '보정동 카페거리 디저트': 'korean dessert cafe pastry',

  // ── 술·음료 ───────────────────────────────────────────────────────
  '모주': 'moju korean traditional sweet rice wine',
  '막걸리': 'makgeolli korean rice wine traditional',
  '교동법주': 'beopju korean traditional rice wine gyeongju',
  '산수유 막걸리': 'cornelian cherry makgeolli korean',
  '솔송주': 'sol song ju pine tree traditional korean alcohol',
  '수제맥주': 'craft beer korean',
  '감귤주스': 'jeju tangerine orange juice korean',
  '용인 막걸리': 'makgeolli korean rice wine yongin traditional',
}

export function cleanKoreanFoodName(name: string): string {
  let cleaned = name.trim()
  for (const city of CITY_NAMES) {
    cleaned = cleaned.replace(new RegExp(`^${city}\\s+`), '').trim()
  }
  return cleaned
}

export function toEnglishQuery(koreanName: string, tags?: string[]): string {
  if (KOREAN_FOOD_MAP[koreanName]) return KOREAN_FOOD_MAP[koreanName]

  const cleaned = cleanKoreanFoodName(koreanName)
  if (KOREAN_FOOD_MAP[cleaned]) return KOREAN_FOOD_MAP[cleaned]

  if (tags && tags.length > 0) {
    return `${tags.slice(0, 2).join(' ')} korean food traditional`
  }
  return `${cleaned} korean food`
}
